import HomePage from "./HomePage";
import QuotePage from "./QuotePage";
import BookPage from "./BookPage";
import StackPage from "./StackPage";
import ContactPage from "./ContactPage";
import BlogPage from "./BlogPage";
import PostPage from "./PostPage";
import TimelinePage from "./TimelinePage";
import NotFoundPage from "./NotFoundPage";

export { HomePage };
export { QuotePage };
export { BookPage };
export { StackPage };
export { ContactPage };
export { BlogPage };
export { PostPage };
export { TimelinePage };
export { NotFoundPage };
